#pragma once

typedef enum _InstructionBehaviour
{
	InstructionBehaviour_Invalid,
	InstructionBehaviour_Add,
	InstructionBehaviour_Or,
	InstructionBehaviour_Adc,
	InstructionBehaviour_Sbb,
	InstructionBehaviour_And,
	InstructionBehaviour_Sub,
	InstructionBehaviour_Xor,
	InstructionBehaviour_Cmp,
	InstructionBehaviour_Push,
	InstructionBehaviour_Pop,
	InstructionBehaviour_Movsxd,
	InstructionBehaviour_Imul,
	InstructionBehaviour_Ins,
	InstructionBehaviour_Outs,
	InstructionBehaviour_Jo,
	InstructionBehaviour_Jno,
	InstructionBehaviour_Jb,
	InstructionBehaviour_Jae,
	InstructionBehaviour_Je,
	InstructionBehaviour_Jne,
	InstructionBehaviour_Jbe,
	InstructionBehaviour_Ja,
	InstructionBehaviour_Js,
	InstructionBehaviour_Jns,
	InstructionBehaviour_Jp,
	InstructionBehaviour_Jnp,
	InstructionBehaviour_Jl,
	InstructionBehaviour_Jge,
	InstructionBehaviour_Jle,
	InstructionBehaviour_Jg,
	InstructionBehaviour_Jmp,
	InstructionBehaviour_Test,
	InstructionBehaviour_Xchg,
	InstructionBehaviour_Mov,
	InstructionBehaviour_Lea,
	InstructionBehaviour_Nop,
	InstructionBehaviour_Fwait,
	InstructionBehaviour_Pushf,
	InstructionBehaviour_Popf,
	InstructionBehaviour_Sahf,
	InstructionBehaviour_Lahf,
	InstructionBehaviour_Movs,
	InstructionBehaviour_Cmps,
	InstructionBehaviour_Stos,
	InstructionBehaviour_Lods,
	InstructionBehaviour_Scas,
	InstructionBehaviour_Rol,
	InstructionBehaviour_Ror,
	InstructionBehaviour_Rcl,
	InstructionBehaviour_Rcr,
	InstructionBehaviour_Shl,
	InstructionBehaviour_Shr,
	InstructionBehaviour_Sar,
	InstructionBehaviour_Ret,
	InstructionBehaviour_Enter,
	InstructionBehaviour_Leave,
	InstructionBehaviour_Int,
	InstructionBehaviour_Iret,
	InstructionBehaviour_Xlat,
	InstructionBehaviour_Fadd,
	InstructionBehaviour_Fmul,
	InstructionBehaviour_Fcom,
	InstructionBehaviour_Fcomp,
	InstructionBehaviour_Fsub,
	InstructionBehaviour_Fsubr,
	InstructionBehaviour_Fdiv,
	InstructionBehaviour_Fdivr,
	InstructionBehaviour_Fld,
	InstructionBehaviour_Fxch,
	InstructionBehaviour_Fst,
	InstructionBehaviour_Fstp,
	InstructionBehaviour_Fnop,
	InstructionBehaviour_Fldenv,
	InstructionBehaviour_Fchs,
	InstructionBehaviour_Fabs,
	InstructionBehaviour_Ftst,
	InstructionBehaviour_Fxam,
	InstructionBehaviour_Fldcw,
	InstructionBehaviour_Fld1,
	InstructionBehaviour_Fldl2t,
	InstructionBehaviour_Fldl2e,
	InstructionBehaviour_Fldpi,
	InstructionBehaviour_Fldlg2,
	InstructionBehaviour_Fldln2,
	InstructionBehaviour_Fldz,
	InstructionBehaviour_Cbw,
	InstructionBehaviour_Cwd,
	InstructionBehaviour_Cdq,
	InstructionBehaviour_Cqo,
	InstructionBehaviour_Fnstenv,
	InstructionBehaviour_Fstenv,
	InstructionBehaviour_F2xm1,
	InstructionBehaviour_Fyl2x,
	InstructionBehaviour_Fptan,
	InstructionBehaviour_Fpatan,
	InstructionBehaviour_Fxtract,
	InstructionBehaviour_Fprem1,
	InstructionBehaviour_Fdecstp,
	InstructionBehaviour_Fincstp,
	InstructionBehaviour_Fnstcw,
	InstructionBehaviour_Fstcw,
	InstructionBehaviour_Fprem,
	InstructionBehaviour_Fyl2xp1,
	InstructionBehaviour_Fsqrt,
	InstructionBehaviour_Fsincos,
	InstructionBehaviour_Frndint,
	InstructionBehaviour_Fscale,
	InstructionBehaviour_Fsin,
	InstructionBehaviour_Fcos,
	InstructionBehaviour_Fiadd,
	InstructionBehaviour_Fcmovb,
	InstructionBehaviour_Fimul,
	InstructionBehaviour_Fcmove,
	InstructionBehaviour_Ficom,
	InstructionBehaviour_Fcmovbe,
	InstructionBehaviour_Ficomp,
	InstructionBehaviour_Fcmovu,
	InstructionBehaviour_Fisub,
	InstructionBehaviour_Fisubr,
	InstructionBehaviour_Fucompp,
	InstructionBehaviour_Fidiv,
	InstructionBehaviour_Fidivr,
	InstructionBehaviour_Fild,
	InstructionBehaviour_Fcmovnb,
	InstructionBehaviour_Fisttp,
	InstructionBehaviour_Fcmovne,
	InstructionBehaviour_Fist,
	InstructionBehaviour_Fcmovnbe,
	InstructionBehaviour_Fistp,
	InstructionBehaviour_Fcmovnu,
	InstructionBehaviour_Fnclex,
	InstructionBehaviour_Fclex,
	InstructionBehaviour_Fninit,
	InstructionBehaviour_Finit,
	InstructionBehaviour_Fucomi,
	InstructionBehaviour_Fcomi,
	InstructionBehaviour_Ffree,
	InstructionBehaviour_Frstor,
	InstructionBehaviour_Fucom,
	InstructionBehaviour_Fucomp,
	InstructionBehaviour_Fnsave,
	InstructionBehaviour_Fsave,
	InstructionBehaviour_Fnstsw,
	InstructionBehaviour_Fstsw,
	InstructionBehaviour_Faddp,
	InstructionBehaviour_Fmulp,
	InstructionBehaviour_Ficompp,
	InstructionBehaviour_Fsubrp,
	InstructionBehaviour_Fsubp,
	InstructionBehaviour_Fdivrp,
	InstructionBehaviour_Fdivp,
	InstructionBehaviour_Ffreep,
	InstructionBehaviour_Fbld,
	InstructionBehaviour_Fucomip,
	InstructionBehaviour_Fbstp,
	InstructionBehaviour_Fcomip,
	InstructionBehaviour_Loopnz,
	InstructionBehaviour_Loopz,
	InstructionBehaviour_Loop,
	InstructionBehaviour_In,
	InstructionBehaviour_Out,
	InstructionBehaviour_Call,
	InstructionBehaviour_Icebp,
	InstructionBehaviour_Hlt,
	InstructionBehaviour_Cmc,
	InstructionBehaviour_Not,
	InstructionBehaviour_Neg,
	InstructionBehaviour_Mul,
	InstructionBehaviour_Div,
	InstructionBehaviour_Idiv,
	InstructionBehaviour_Clc,
	InstructionBehaviour_Stc,
	InstructionBehaviour_Cli,
	InstructionBehaviour_Sti,
	InstructionBehaviour_Cld,
	InstructionBehaviour_Std,
	InstructionBehaviour_Inc,
	InstructionBehaviour_Dec,
	InstructionBehaviour_Sldt,
	InstructionBehaviour_Str,
	InstructionBehaviour_Lldt,
	InstructionBehaviour_Ltr,
	InstructionBehaviour_Verr,
	InstructionBehaviour_Verw,
	InstructionBehaviour_Sgdt,
	InstructionBehaviour_Enclv,
	InstructionBehaviour_Vmcall,
	InstructionBehaviour_Vmlaunch,
	InstructionBehaviour_Vmresume,
	InstructionBehaviour_Vmxoff,
	InstructionBehaviour_Pconfig,
	InstructionBehaviour_Sidt,
	InstructionBehaviour_Monitor,
	InstructionBehaviour_Mwait,
	InstructionBehaviour_Clac,
	InstructionBehaviour_Stac,
	InstructionBehaviour_Lgdt,
	InstructionBehaviour_Xgetbv,
	InstructionBehaviour_Xsetbv,
	InstructionBehaviour_Vmfunc,
	InstructionBehaviour_Xend,
	InstructionBehaviour_Xtest,
	InstructionBehaviour_Enclu,
	InstructionBehaviour_Lidt,
	InstructionBehaviour_Vmrun,
	InstructionBehaviour_Vmmcall,
	InstructionBehaviour_Vmload,
	InstructionBehaviour_Vmsave,
	InstructionBehaviour_Stgi,
	InstructionBehaviour_Clgi,
	InstructionBehaviour_Skinit,
	InstructionBehaviour_Invlpga,
	InstructionBehaviour_Smsw,
	InstructionBehaviour_Serialize,
	InstructionBehaviour_Rdpkru,
	InstructionBehaviour_Wrpkru,
	InstructionBehaviour_Lmsw,
	InstructionBehaviour_Invlpg,
	InstructionBehaviour_Swapgs,
	InstructionBehaviour_Rdiscp,
	InstructionBehaviour_Monitorx,
	InstructionBehaviour_Mwaitx,
	InstructionBehaviour_Clzero,
	InstructionBehaviour_Rdpru,
	InstructionBehaviour_Lar,
	InstructionBehaviour_Lsl,
	InstructionBehaviour_Syscall,
	InstructionBehaviour_Clts,
	InstructionBehaviour_Sysret,
	InstructionBehaviour_Invd,
	InstructionBehaviour_Wbinvd,
	InstructionBehaviour_Movups,
	InstructionBehaviour_Movss,
	InstructionBehaviour_Movupd,
	InstructionBehaviour_Movsd,
	InstructionBehaviour_Movhlps,
	InstructionBehaviour_Movlps,
	InstructionBehaviour_Movlpd,
	InstructionBehaviour_Movddup,
	InstructionBehaviour_Movsldup,
	InstructionBehaviour_Unpcklps,
	InstructionBehaviour_Unpcklpd,
	InstructionBehaviour_Unpckhps,
	InstructionBehaviour_Unpckhpd,
	InstructionBehaviour_Movlhps,
	InstructionBehaviour_Movhps,
	InstructionBehaviour_Movhpd,
	InstructionBehaviour_Movshdup,
	InstructionBehaviour_Prefetchnta,
	InstructionBehaviour_Prefetcht0,
	InstructionBehaviour_Prefetcht1,
	InstructionBehaviour_Prefetcht2,
	InstructionBehaviour_Movaps,
	InstructionBehaviour_Movapd,
	InstructionBehaviour_Cvtpi2ps,
	InstructionBehaviour_Cvtsi2ss,
	InstructionBehaviour_Cvtpi2pd,
	InstructionBehaviour_Cvtsi2sd,
	InstructionBehaviour_Movntps,
	InstructionBehaviour_Movntpd,
	InstructionBehaviour_Cvttps2pi,
	InstructionBehaviour_Cvttss2si,
	InstructionBehaviour_Cvttpd2pi,
	InstructionBehaviour_Cvttsd2si,
	InstructionBehaviour_Cvtps2pi,
	InstructionBehaviour_Cvtss2si,
	InstructionBehaviour_Cvtpd2pi,
	InstructionBehaviour_Cvtsd2si,
	InstructionBehaviour_Ucomiss,
	InstructionBehaviour_Ucomisd,
	InstructionBehaviour_Comiss,
	InstructionBehaviour_Comisd,
	InstructionBehaviour_Wrmsr,
	InstructionBehaviour_Rdtsc,
	InstructionBehaviour_Rdmsr,
	InstructionBehaviour_Rdpmc,
	InstructionBehaviour_Sysenter,
	InstructionBehaviour_Sysexit,
	InstructionBehaviour_Getsec,
	InstructionBehaviour_Invept,
	InstructionBehaviour_Invvpid,
	InstructionBehaviour_Movbe,
	InstructionBehaviour_Crc32,
	InstructionBehaviour_Roundps,
	InstructionBehaviour_Roundpd,
	InstructionBehaviour_Roundss,
	InstructionBehaviour_Roundsd,
	InstructionBehaviour_Blendps,
	InstructionBehaviour_Blendpd,
	InstructionBehaviour_Pblendw,
	InstructionBehaviour_Palignr,
	InstructionBehaviour_Pextrb,
	InstructionBehaviour_Pextrw,
	InstructionBehaviour_Pextr,
	InstructionBehaviour_Extractps,
	InstructionBehaviour_Pinsrb,
	InstructionBehaviour_Insertps,
	InstructionBehaviour_Pinsr,
	InstructionBehaviour_Dpps,
	InstructionBehaviour_Dppd,
	InstructionBehaviour_Mpsadbw,
	InstructionBehaviour_Pcmpestrm,
	InstructionBehaviour_Pcmpestri,
	InstructionBehaviour_Pcmpistrm,
	InstructionBehaviour_Pcmpistri,
	InstructionBehaviour_Cmovo,
	InstructionBehaviour_Cmovno,
	InstructionBehaviour_Cmovb,
	InstructionBehaviour_Cmovae,
	InstructionBehaviour_Cmove,
	InstructionBehaviour_Cmovne,
	InstructionBehaviour_Cmovbe,
	InstructionBehaviour_Cmova,
	InstructionBehaviour_Cmovs,
	InstructionBehaviour_Cmovns,
	InstructionBehaviour_Cmovp,
	InstructionBehaviour_Cmovnp,
	InstructionBehaviour_Cmovl,
	InstructionBehaviour_Cmovge,
	InstructionBehaviour_Cmovle,
	InstructionBehaviour_Cmovg,
	InstructionBehaviour_Movmskps,
	InstructionBehaviour_Movmskpd,
	InstructionBehaviour_Sqrtps,
	InstructionBehaviour_Sqrtss,
	InstructionBehaviour_Sqrtpd,
	InstructionBehaviour_Sqrtsd,
	InstructionBehaviour_Rsqrtps,
	InstructionBehaviour_Rsqrtss,
	InstructionBehaviour_Rcpps,
	InstructionBehaviour_Rcpss,
	InstructionBehaviour_Andps,
	InstructionBehaviour_Andpd,
	InstructionBehaviour_Andnps,
	InstructionBehaviour_Andnpd,
	InstructionBehaviour_Orps,
	InstructionBehaviour_Orpd,
	InstructionBehaviour_Xorps,
	InstructionBehaviour_Xorpd,
	InstructionBehaviour_Addps,
	InstructionBehaviour_Addss,
	InstructionBehaviour_Addpd,
	InstructionBehaviour_Addsd,
	InstructionBehaviour_Mulps,
	InstructionBehaviour_Mulss,
	InstructionBehaviour_Mulpd,
	InstructionBehaviour_Mulsd,
	InstructionBehaviour_Cvtps2pd,
	InstructionBehaviour_Cvtpd2ps,
	InstructionBehaviour_Cvtss2sd,
	InstructionBehaviour_Cvtsd2ss,
	InstructionBehaviour_Cvtdq2ps,
	InstructionBehaviour_Cvtps2dq,
	InstructionBehaviour_Cvttps2dq,
	InstructionBehaviour_Subps,
	InstructionBehaviour_Subss,
	InstructionBehaviour_Subpd,
	InstructionBehaviour_Subsd,
	InstructionBehaviour_Minps,
	InstructionBehaviour_Minss,
	InstructionBehaviour_Minpd,
	InstructionBehaviour_Minsd,
	InstructionBehaviour_Divps,
	InstructionBehaviour_Divss,
	InstructionBehaviour_Divpd,
	InstructionBehaviour_Divsd,
	InstructionBehaviour_Maxps,
	InstructionBehaviour_Maxss,
	InstructionBehaviour_Maxpd,
	InstructionBehaviour_Maxsd,
	InstructionBehaviour_Punpcklbw,
	InstructionBehaviour_Punpcklwd,
	InstructionBehaviour_Punpckldq,
	InstructionBehaviour_Packsswb,
	InstructionBehaviour_Pcmpgtb,
	InstructionBehaviour_Pcmpgtw,
	InstructionBehaviour_Pcmpgtd,
	InstructionBehaviour_Packuswb,
	InstructionBehaviour_Punpckhbw,
	InstructionBehaviour_Punpckhwd,
	InstructionBehaviour_Punpckhdq,
	InstructionBehaviour_Packssdw,
	InstructionBehaviour_Punpcklqdq,
	InstructionBehaviour_Punpckhqdq,
	InstructionBehaviour_Movq,
	InstructionBehaviour_Movdqa,
	InstructionBehaviour_Movdqu,
	InstructionBehaviour_Pshufw,
	InstructionBehaviour_Pshuflw,
	InstructionBehaviour_Pshufhw,
	InstructionBehaviour_Pshufd,
	InstructionBehaviour_Psrlw,
	InstructionBehaviour_Psraw,
	InstructionBehaviour_Psllw,
	InstructionBehaviour_Psrld,
	InstructionBehaviour_Psrad,
	InstructionBehaviour_Pslld,
	InstructionBehaviour_Psrlq,
	InstructionBehaviour_Psrldq,
	InstructionBehaviour_Psllq,
	InstructionBehaviour_Pslldq,
	InstructionBehaviour_Pcmpeqb,
	InstructionBehaviour_Pcmpeqw,
	InstructionBehaviour_Pcmpeqd,
	InstructionBehaviour_Emms,
	InstructionBehaviour_Vmread,
	InstructionBehaviour_Vmwrite,
	InstructionBehaviour_Haddpd,
	InstructionBehaviour_Haddps,
	InstructionBehaviour_Hsubpd,
	InstructionBehaviour_Hsubps,
	InstructionBehaviour_Seto,
	InstructionBehaviour_Setno,
	InstructionBehaviour_Setb,
	InstructionBehaviour_Setae,
	InstructionBehaviour_Sete,
	InstructionBehaviour_Setne,
	InstructionBehaviour_Setbe,
	InstructionBehaviour_Seta,
	InstructionBehaviour_Sets,
	InstructionBehaviour_Setns,
	InstructionBehaviour_Setp,
	InstructionBehaviour_Setnp,
	InstructionBehaviour_Setl,
	InstructionBehaviour_Setge,
	InstructionBehaviour_Setle,
	InstructionBehaviour_Setg,
	InstructionBehaviour_Cpuid,
	InstructionBehaviour_Bt,
	InstructionBehaviour_Shld,
	InstructionBehaviour_Rsm,
	InstructionBehaviour_Bts,
	InstructionBehaviour_Shrd,
	InstructionBehaviour_Fxsave,
	InstructionBehaviour_Fxrstor,
	InstructionBehaviour_Ldmxcsr,
	InstructionBehaviour_Stmxcsr,
	InstructionBehaviour_Xsave,
	InstructionBehaviour_Lfence,
	InstructionBehaviour_Xrstor,
	InstructionBehaviour_Xsaveopt,
	InstructionBehaviour_Mfence,
	InstructionBehaviour_Sfence,
	InstructionBehaviour_Clflush,
	InstructionBehaviour_Cmpxchg,
	InstructionBehaviour_Lss,
	InstructionBehaviour_Btr,
	InstructionBehaviour_Lfs,
	InstructionBehaviour_Lgs,
	InstructionBehaviour_Movzx,
	InstructionBehaviour_Popcnt,
	InstructionBehaviour_Btc,
	InstructionBehaviour_Bsf,
	InstructionBehaviour_Bsr,
	InstructionBehaviour_Movsx,
	InstructionBehaviour_Xadd,
	InstructionBehaviour_Cmpps,
	InstructionBehaviour_Cmpss,
	InstructionBehaviour_Cmppd,
	InstructionBehaviour_Cmpsd,
	InstructionBehaviour_Movnti,
	InstructionBehaviour_Pinsrw,
	InstructionBehaviour_Shufps,
	InstructionBehaviour_Shufpd,
	InstructionBehaviour_Vmptrld,
	InstructionBehaviour_Vmclear,
	InstructionBehaviour_Vmxon,
	InstructionBehaviour_Vmptrst,
	InstructionBehaviour_Bswap,
	InstructionBehaviour_Addsubpd,
	InstructionBehaviour_Addsubps,
	InstructionBehaviour_Paddq,
	InstructionBehaviour_Pmullw,
	InstructionBehaviour_Movq2dq,
	InstructionBehaviour_Movdq2q,
	InstructionBehaviour_Pmovmskb,
	InstructionBehaviour_Psubusb,
	InstructionBehaviour_Psubusw,
	InstructionBehaviour_Pminub,
	InstructionBehaviour_Pand,
	InstructionBehaviour_Paddusb,
	InstructionBehaviour_Paddusw,
	InstructionBehaviour_Pmaxub,
	InstructionBehaviour_Pandn,
	InstructionBehaviour_Pavgb,
	InstructionBehaviour_Pavgw,
	InstructionBehaviour_Pmulhuw,
	InstructionBehaviour_Pmulhw,
	InstructionBehaviour_Cvtpd2dq,
	InstructionBehaviour_Cvttpd2dq,
	InstructionBehaviour_Cvtdq2pd,
	InstructionBehaviour_Movntq,
	InstructionBehaviour_Movntdq,
	InstructionBehaviour_Psubsb,
	InstructionBehaviour_Psubsw,
	InstructionBehaviour_Pminsw,
	InstructionBehaviour_Por,
	InstructionBehaviour_Paddsb,
	InstructionBehaviour_Paddsw,
	InstructionBehaviour_Pmaxsw,
	InstructionBehaviour_Pxor,
	InstructionBehaviour_Lddqu,
	InstructionBehaviour_Pmuludq,
	InstructionBehaviour_Pmaddwd,
	InstructionBehaviour_Psadbw,
	InstructionBehaviour_Maskmovq,
	InstructionBehaviour_Maskmovdqu,
	InstructionBehaviour_Psubb,
	InstructionBehaviour_Psubw,
	InstructionBehaviour_Psubd,
	InstructionBehaviour_Psubq,
	InstructionBehaviour_Paddb,
	InstructionBehaviour_Paddw,
	InstructionBehaviour_Paddd,
} InstructionBehaviour, * PInstructionBehaviour;

typedef enum _OperandType
{
	OperandType_None,

	OperandType_SR,	// Segment register
	OperandType_IR,	// Integer register
	OperandType_FR, // Floating register
	OperandType_CR, // Control register
	OperandType_VR, // Vector register
	OperandType_DR, // Debug register
	OperandType_QR, // Quad register

	OperandType_M,	// Memory
	OperandType_ML,	// Memory large
	OperandType_V,	// Value
	OperandType_Rel // Relative value
} OperandType, * POperandType;

typedef enum _OperationType
{
	OperationType_Normal,
	OperationType_Locked,
	OperationType_RepeatZ,
	OperationType_RepeatNotZ,
	OperationType_OperandLess
} OperationType, * POperationType;

typedef enum _OperationSize
{
	OperationSize_None,
	OperationSize_8,
	OperationSize_16,
	OperationSize_32,
	OperationSize_64,
	OperationSize_80,
	OperationSize_128,
} OperationSize, * POperationSize;

typedef enum _MemoryOffsetSize
{
	MemoryOffsetSize_0,
	MemoryOffsetSize_8,
	MemoryOffsetSize_32
} MemoryOffsetSize, *PMemoryOffsetSize;

#pragma pack(push, 1)

typedef struct _Operand // Registers are counted 1 ... 254, 255 reserved for relativity
{
	struct
	{
		unsigned char Type : 4;
		unsigned char OperandSize : 4;
	};
	union
	{
		struct
		{
			unsigned char Register;
			unsigned char HighLowPart; // Low part 0, High part 1
		} Register;

		struct
		{
			unsigned char FirstRegister;
			unsigned char SecondRegister;

			struct
			{
				unsigned char Segment : 4;
				unsigned char Multiplier : 2;
				unsigned char OffsetSize : 2;
			};

			long Offset;
		} Memory;

		struct
		{
			unsigned long long Value;
		} MemoryLarge;

		struct
		{
			unsigned long long Value;
		} Value;

		struct
		{
			long Value;
		} RelValue;
	};
} Operand, * POperand;

typedef struct _Operation
{
	struct
	{
		unsigned short Type : 3;
		unsigned short Behaviour : 13;
	};
	union
	{
		struct
		{
			Operand Operands[4];
		} N;

		struct
		{
			OperationSize OperationSize;
		} OL;
	};
} Operation, * POperation;

#pragma pack(pop)